"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import Link from "next/link";
import { CheckCheck, PlayCircle, BellOff } from "lucide-react";
import { Card } from "@/components/admin/ui/Card";
import { Button } from "@/components/admin/ui/Button";
import { markNotificationRead, markAllNotificationsRead, runAutomationSweepAction } from "@/lib/admin/actions/notification-actions";
import { formatDate } from "@/lib/utils";
import type { Database } from "@/types/database.types";

type Notification = Database["public"]["Tables"]["edoscentreadmin_notifications"]["Row"];

const SEVERITY_STYLES: Record<string, string> = {
  info: "bg-sky-50 text-sky-700 ring-sky-600/20",
  warning: "bg-amber-50 text-amber-700 ring-amber-600/20",
  critical: "bg-red-50 text-red-700 ring-red-600/20",
};

export default function NotificationsPanel({ notifications, canRunSweep }: { notifications: Notification[]; canRunSweep: boolean }) {
  const router = useRouter();
  const [pending, setPending] = useState(false);
  const unreadCount = notifications.filter((n) => !n.is_read).length;

  async function onMarkRead(id: string) {
    try {
      await markNotificationRead(id);
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Unable to mark as read.");
    }
  }

  async function onMarkAllRead() {
    try {
      await markAllNotificationsRead();
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Unable to mark all as read.");
    }
  }

  async function onRunSweep() {
    setPending(true);
    try {
      const result = await runAutomationSweepAction();
      toast.success(
        `Sweep complete — ${result.subscriptionsUpdated} subscription${result.subscriptionsUpdated === 1 ? "" : "s"} updated, ${result.invoicesUpdated} invoice${result.invoicesUpdated === 1 ? "" : "s"} marked overdue, ${result.notificationsCreated} new alert${result.notificationsCreated === 1 ? "" : "s"}.`,
      );
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Sweep failed.");
    } finally {
      setPending(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900">Notifications</h1>
          <p className="mt-1 text-sm text-slate-500">
            {unreadCount === 0 ? "You're all caught up." : `${unreadCount} unread`} — generated by the automation sweep from subscription, invoice, domain and SSL dates.
          </p>
        </div>
        <div className="flex gap-2">
          {unreadCount > 0 && (
            <Button variant="secondary" onClick={onMarkAllRead}>
              <CheckCheck className="h-4 w-4" /> Mark all read
            </Button>
          )}
          {canRunSweep && (
            <Button onClick={onRunSweep} loading={pending}>
              <PlayCircle className="h-4 w-4" /> Run automation sweep now
            </Button>
          )}
        </div>
      </div>

      <Card className="overflow-hidden">
        {notifications.length === 0 ? (
          <div className="flex flex-col items-center gap-2 py-12 text-center text-sm text-slate-400">
            <BellOff className="h-8 w-8 text-slate-300" />
            <p>No notifications yet.</p>
            {canRunSweep && <p className="text-xs text-slate-300">Run the automation sweep to check for anything that needs attention.</p>}
          </div>
        ) : (
          <ul className="divide-y divide-slate-100">
            {notifications.map((n) => (
              <li key={n.id} className={`flex items-start justify-between gap-4 px-5 py-4 ${n.is_read ? "" : "bg-slate-50/60"}`}>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset ${SEVERITY_STYLES[n.severity] ?? SEVERITY_STYLES.info}`}>
                      {n.severity}
                    </span>
                    {n.link ? (
                      <Link href={n.link} className="truncate font-medium text-slate-900 hover:underline">
                        {n.title}
                      </Link>
                    ) : (
                      <span className="truncate font-medium text-slate-900">{n.title}</span>
                    )}
                  </div>
                  {n.message && <p className="mt-1 text-sm text-slate-500">{n.message}</p>}
                  <p className="mt-1 text-xs text-slate-400">{formatDate(n.created_at)}</p>
                </div>
                {!n.is_read && (
                  <button onClick={() => onMarkRead(n.id)} className="shrink-0 rounded-lg border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-600 hover:bg-slate-50">
                    Mark read
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}
