-- ============================================================================
-- Migration 013 – Notifications & Automation (Phase 6)
-- ============================================================================
-- Notifications generated by the automation sweep (subscription lifecycle,
-- overdue invoices, expiring domains/SSL) and delivered per-admin. The sweep
-- itself runs server-side via the service-role client (a cron-triggered API
-- route, or the "Run automation now" button) — this table only stores what it
-- produces.
--
-- dedup_key + the unique constraint below is what stops the sweep from
-- spamming the same admin with the same alert every time it runs: each
-- distinct state (e.g. "domain X entered its final 7 days") gets exactly one
-- notification, via ON CONFLICT DO NOTHING upserts.
-- ============================================================================

CREATE TABLE IF NOT EXISTS edoscentreadmin_notifications (
  id           UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  recipient_id UUID        NOT NULL REFERENCES edoscentreadmin_admin_users(id) ON DELETE CASCADE,
  type         TEXT        NOT NULL,
  severity     TEXT        NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  title        TEXT        NOT NULL,
  message      TEXT,
  link         TEXT,
  dedup_key    TEXT        NOT NULL,
  is_read      BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (recipient_id, dedup_key)
);

CREATE INDEX IF NOT EXISTS idx_edoscentreadmin_notifications_recipient ON edoscentreadmin_notifications (recipient_id, is_read, created_at DESC);

ALTER TABLE edoscentreadmin_notifications ENABLE ROW LEVEL SECURITY;

-- Admins only ever see/update their own notifications. Inserts happen from the
-- service-role automation sweep only, so no INSERT/DELETE policy is granted here.
DROP POLICY IF EXISTS eca_notifications_select_own ON edoscentreadmin_notifications;
CREATE POLICY eca_notifications_select_own ON edoscentreadmin_notifications
  FOR SELECT USING (recipient_id = auth.uid());

DROP POLICY IF EXISTS eca_notifications_update_own ON edoscentreadmin_notifications;
CREATE POLICY eca_notifications_update_own ON edoscentreadmin_notifications
  FOR UPDATE USING (recipient_id = auth.uid()) WITH CHECK (recipient_id = auth.uid());
